// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Data$MapovaniMotyly = require("./Data.bs.js");

var resolvers = {
  author: (function (post) {
      var match = Data$MapovaniMotyly.authors.find((function (author) {
              return +(author.id === post.authorId);
            }));
      if (match !== undefined) {
        return match;
      } else {
        return undefined;
      }
    })
};

var typeDef = "\n  type Post {\n    id: Int!\n    title: String\n    author: Author\n    votes: Int\n  }\n";

exports.typeDef = typeDef;
exports.resolvers = resolvers;
/* No side effect */
